create sequence item_seq start with 1 increment by 50;
create sequence location_seq start with 1 increment by 50;
create sequence shipment_seq start with 1 increment by 50;
create table item (item_id bigint not null, primary key (item_id));
create table location (post_code integer not null, location_id bigint not null, address varchar(255) not null, city varchar(255), country varchar(255) not null, primary key (location_id));
create table shipment (created date not null, delivery_estimate date not null, status tinyint not null check (status between 0 and 11), billing_address_location_id bigint not null, customer_id bigint not null, delivery_address_location_id bigint not null, shipment_id bigint not null, primary key (shipment_id));
create table shipment_item_ids (item_ids_item_id bigint not null unique, shipment_shipment_id bigint not null);
alter table if exists shipment add constraint FKi1b45ekv9rtk9u3ntpyblcqt2 foreign key (billing_address_location_id) references location;
alter table if exists shipment add constraint FKnjbgsxmt8hb5ng6rtvbf1oysp foreign key (delivery_address_location_id) references location;
alter table if exists shipment_item_ids add constraint FK61gsgggn58ol433ccsp8ykxt1 foreign key (item_ids_item_id) references item;
alter table if exists shipment_item_ids add constraint FKfhge5dx3w8ksmkydgqudqgk2b foreign key (shipment_shipment_id) references shipment;
create sequence items_seq start with 1 increment by 50;
create sequence location_seq start with 1 increment by 50;
create sequence shipment_seq start with 1 increment by 50;
create table items (item_id bigint not null, primary key (item_id));
create table location (post_code integer not null, location_id bigint not null, address varchar(255) not null, city varchar(255), country varchar(255) not null, primary key (location_id));
create table shipment (created date not null, delivery_estimate date not null, status tinyint not null check (status between 0 and 11), billing_address_location_id bigint not null, customer_id bigint not null, delivery_address_location_id bigint not null, shipment_id bigint not null, primary key (shipment_id));
create table shipment_item_ids (item_ids_item_id bigint not null unique, shipment_shipment_id bigint not null);
alter table if exists shipment add constraint FKi1b45ekv9rtk9u3ntpyblcqt2 foreign key (billing_address_location_id) references location;
alter table if exists shipment add constraint FKnjbgsxmt8hb5ng6rtvbf1oysp foreign key (delivery_address_location_id) references location;
alter table if exists shipment_item_ids add constraint FKjsd657pd0h6kk2dr5l8h4elyd foreign key (item_ids_item_id) references items;
alter table if exists shipment_item_ids add constraint FKfhge5dx3w8ksmkydgqudqgk2b foreign key (shipment_shipment_id) references shipment;